language: php
services:
  - mysql
php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm
before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-dist
  - mysql -e 'create database shot;'
  - cp .env.travis .env
  - php artisan migrate --force
  - php artisan db:seed --force
script:
  - phpunit --coverage-text --coverage-clover=coverage.clover
