# Usefull links
# =============
# https://hub.docker.com/_/php/
# https://docs.docker.com/compose/overview/
# https://docs.docker.com/compose/compose-file/
#
# Usefull commands
# ================
#
# Start containers
# $ docker-compose up -d
#
# View running containers
# $ docker-compose ps
#
# Connect into command line of running container
# $ docker-compose run <container_name> bash
# where <name> could be fpm_shot, web_shot, db_shot.
# Container `fpm_shot` is most interesting as it has PHP, application code and connection to databse.
# Tip: `Ctrl+p` + `Ctrl+q` + `Enter` (to exit container bash)
#
# View docker logs
# $ docker-compose logs
#
# Stop containers
# $ docker-compose down
#
# Remove images
# $ docker rmi limoncelloshot_fpm

web:
  image: nginx
  container_name: web_shot
  ports:
    - "8080:80"
  links:
    - fpm
  volumes:
    - .:/app
    - ./docker/nginx.site:/etc/nginx/conf.d/default.conf:ro
    - ./docker/.env.app:/app/.env:ro

fpm:
  build: ./docker/fpm
  container_name: fpm_shot
  links:
    - db
    - logs
  volumes:
    - .:/app
    - ./docker/.env.app:/app/.env:ro
  working_dir: /app

db:
  image: percona
  container_name: db_shot
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_USER: shot
    MYSQL_PASSWORD: secret
    MYSQL_DATABASE: shot

logs:
  image: graylog2/allinone
  container_name: logs_shot
  ports:
    - "8090:9000"
  environment:
    GRAYLOG_USERNAME: admin
    GRAYLOG_PASSWORD: admin
